=== sfeu/MINT-platform/core/model/mim/mint-mappings.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.multi-access.de" xmlns:mint="http://www.multi-access.de" elementFormDefault="qualified">

  <xs:element name="event">
    <xs:complexType>
      <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
      <xs:attribute name="type" type="xs:string" use="required"/>
      <xs:attribute name="target" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="backend">
    <xs:complexType>
      <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
      <xs:attribute name="call" type="xs:string" use="required"/>
      <xs:attribute name="class" type="xs:string" use="required"/>
      <xs:attribute name="parameter" type="xs:string"/>
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="processType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="onchange"/>
      <xs:enumeration value="continuous"/>
      <xs:enumeration value="instant"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="observationType">
      <xs:restriction base="xs:string">
        <xs:enumeration value="negation"/>
      </xs:restriction>
    </xs:simpleType>


  <xs:element name="observation"  >
    <xs:complexType>
      <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
      <xs:attribute name="interactor" type="xs:string" use="required"/>
      <xs:attribute name="name" type="xs:string" />
      <xs:attribute name="states" type="xs:string"/>
      <xs:attribute name="result" type="xs:string"/>
      <xs:attribute name="type" type="observationType"/>
      <xs:attribute name="process" type="processType"/>
    </xs:complexType>

  </xs:element>

  <xs:element name="bind" >
    <xs:complexType>
      <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
      <xs:attribute name="interactor_in" type="xs:string" use="required"/>
      <xs:attribute name="name_in" type="xs:string" use="required"/>
      <xs:attribute name="attr_in" type="xs:string" use="required"/>
      <xs:attribute name="interactor_out" type="xs:string" use="required"/>
      <xs:attribute name="transformation"  type="xs:string"/>  <!-- TODO: if exists transformation, class need to be there as well -->
      <xs:attribute name="class" type="xs:string" />
      <xs:attribute name="name_out" type="xs:string" use="required"/>
      <xs:attribute name="attr_out" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="observations">
    <xs:complexType>
      <xs:sequence minOccurs="1" maxOccurs="unbounded">
        <xs:element ref="mint:observation"  />
      </xs:sequence>
    </xs:complexType>
    <!-- TODO unique check does not work yet -->
    <!--xs:key name="key_Participant">
           <xs:selector xpath="./observation"/>
           <xs:field xpath="@id"/>
         </xs:key-->
  </xs:element>

  <xs:element name="actions">
    <xs:complexType>                           <xs:choice minOccurs="1" maxOccurs="unbounded">
        <xs:element ref="mint:bind" />
        <xs:element ref="mint:event" />
        <xs:element ref="mint:backend" />
      </xs:choice>
    </xs:complexType>
  </xs:element>

  <xs:element name="operator">
    <xs:complexType>
      <xs:sequence minOccurs="1" maxOccurs="1">
        <xs:element ref="mint:observations"/>
        <xs:element ref="mint:actions"/>
      </xs:sequence>
      <xs:attribute name="type" type="xs:string" use="required"/>
      <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="mapping">
     <xs:complexType>
       <xs:sequence>
         <xs:element minOccurs="1" maxOccurs="unbounded" ref="mint:operator"/>
       </xs:sequence>
       <xs:attribute name="name" type="xs:string" use="required"/>

     </xs:complexType>


   </xs:element>

  <xs:element name="include" >
      <xs:complexType>
        <xs:attribute name="href" type="xs:string" use="required"/>
        <xs:attribute name="start" type="xs:string" default="false"/>
      </xs:complexType>
    </xs:element>

  <xs:element name="mim">
     <xs:complexType>
       <xs:choice minOccurs="1" maxOccurs="unbounded">
         <xs:element ref="mint:mapping" />
         <xs:element ref="mint:include"/>
       </xs:choice>
       <xs:attribute name="name" type="xs:string" use="required"/>

     </xs:complexType>
   </xs:element>


</xs:schema>

=== sfeu/MINT-platform/examples/easylibras/mim/load_video.xml
<mapping name="Load Video Execution" xmlns="http://www.multi-access.de"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.multi-access.de ../../../MINT-core/lib/MINT-core/model/mim/mint-mappings.xsd">

  <operator id="1" type="sequential">
    <observations>
      <observation id="2" interactor="Interactor.Learningcycle" name="learner" states="load_video" result="c" process="onchange" />
      <observation id="3" interactor="Interactor.CIO.HTMLWidget.VideoPlayer" name="libras_video"  result="video" process="instant"/>
    </observations>
    <actions>
      <backend id="4" call="setVideo" class="EasyLibrasBackend" parameter="c" />
      <event id="5" type="load_video" target="video"/>
    </actions>
  </operator>

</mapping>

=== sfeu/MINT-platform/core/model/mim/mouse_press_to_aicommand_activate.xml
<mapping name="Sync Mouse press to AICommand activate" xmlns="http://www.multi-access.de"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.multi-access.de mint-mappings.xsd">

  <operator type="sequential" id="1">
    <observations>
      <observation id="2" interactor="Interactor.IR.IRMode.Pointer.Mouse" states="left_pressed" process="onchange"/>
      <observation id="3" interactor="Interactor.AIO.AIIN.AIINDiscrete.AIReference.AICommand" states="focused" result="c" process="instant"/>
      <observation id="4" interactor="Interactor.AIO.AIIN.AIINDiscrete.AIReference.AICommand" name="c.name" states="deactivated" process="instant"/>
    </observations>
    <actions>
      <event id="5" type="activate" target="c"/>
    </actions>
  </operator>

</mapping>

=== sfeu/MINT-platform/examples/luminar/mim/mim_luminar_example.xml
<?xml version='1.0'?>
<mim name="Streaming Example" xmlns="http://www.multi-access.de"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://www.multi-access.de ../../../../MINT-core/lib/MINT-core/model/mim/mint-mappings.xsd">

  <include href="../../../../MINT-core/lib/MINT-core/model/mim/browserscreen_reload_to_cuicontrol_refresh_all.xml" start="true" />
  <include href="../../../../MINT-core/lib/MINT-core/model/mim/mouse_stop_to_cio_highlight.xml" start="true" />

  <include href="../../../../MINT-core/lib/MINT-core/model/mim/cio_hide_to_cio_display_cache_remove.xml" start="true" />
  <include href="../../../../MINT-core/lib/MINT-core/model/mim/cio_display_to_cio_display_cache_add.xml" start="true" />

  <include href="../../../../MINT-core/lib/MINT-core/model/mim/aio_defocus_to_cio_unhighlight.xml" start="true" />
  <include href="../../../../MINT-core/lib/MINT-core/model/mim/aio_present_to_cio_display.xml" start="true" />
  <include href="../../../../MINT-core/lib/MINT-core/model/mim/aio_suspend_to_cio_hide.xml" start="true" />
  <!-- Gesture-based Navigation -->

  <include href="fingertip_stop_to_cio_highlight.xml" start="true"/>
  <!--include href="reset_execution.xml" start="true"/-->
  <include href="fingertip_touched_to_aicommand_activate.xml" start="true"/>
  <!--include href="mouse_press_to_aicommand_activate.xml" start="true"/-->
</mim>

=== sfeu/MINT-platform/core/model/mim/cio_display_to_aio_defocus.xml
<mapping name="Sync CIO display to AIC defocus" xmlns="http://www.multi-access.de" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.multi-access.de mint-mappings.xsd">
  <operator type="sequential" id="1">
    <observations>
      <observation id="2" interactor="Interactor.CIO" states="displayed" result="cio" process="onchange"/>
      <observation id="3" type="negation" interactor="Interactor.AIO" name="cio.name" states="defocused" result="aio" process="instant"/>
      <observation id="5" interactor="Interactor.CIO" name="cio.name" states="displayed" process="instant"/>
    </observations>
    <actions>
      <event id="4" type="defocus" target="aio"/>
    </actions>
  </operator>
</mapping>

=== sfeu/MINT-platform/core/model/mim/mim_default.xml
<?xml version='1.0'?>
<mim name="Default Sync Mappings" xmlns="http://www.multi-access.de"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://www.multi-access.de mint-mappings.xsd">

  <include href="browserscreen_reload_to_cio_hidden_refresh.xml" start="true" />
  <include href="browserscreen_reload_to_cio_displaying_refresh.xml" start="true" />
  <include href="mouse_stop_to_cio_highlight.xml" start="true" />
  <include href="mouse_press_to_aicommand_activate.xml" start="true" />
  <include href="mouse_release_to_aicommand_deactivate.xml" start="true" />
  <!--include href="aicommand_activate_to_button_press.xml" start="true" />
  <include href="aicommand_deactivate_to_button_release.xml" start="true" /-->
  <include href="aio_defocus_to_cio_unhighlight.xml" start="true" />
  <include href="aio_focus_to_cio_highlight.xml" start="true" />
  <include href="aio_present_to_cio_display.xml" start="true" />
  <include href="aio_suspend_to_cio_hide.xml" start="true" />
  <include href="button_press_to_aicommand_activate.xml" start="true" />
  <include href="button_release_to_aicommand_deactivate.xml" start="true" />
  <include href="left_button_aisinglepresence_enter.xml" start="true"/>

  <!--include href="cio_display_to_aio_defocus.xml" start="true" />
  <include href="cio_display_to_aio_present.xml" start="true" />
  <include href="cio_hide_to_aio_suspend.xml" start="true" />
  <include href="cio_highlight_to_aio_focus.xml" start="true" /-->
  <include href="cio_hide_to_cio_display_cache_remove.xml" start="true" />
  <include href="cio_display_to_cio_display_cache_add.xml" start="true" />
  <include href="aisinglepresence_present_to_child_present.xml" start="true" />
  <include href="aisinglepresence_children_finished_to_caroufredsel_init_js.xml" start="true" />
  <include href="aisinglechoice_present_to_child_present.xml" start="true" />
  <include href="aisinglechoiceelement_unchosen_to_radiobutton_unselect.xml" start="true" />
  <include href="aisinglechoiceelement_chosen_to_radiobutton_select.xml" start="true" />
  <include href="radiobutton_unselected_to_aisinglechoiceelement_unchoose.xml" start="true" />
  <include href="radiobutton_selected_to_aisinglechoiceelement_choose.xml" start="true" />
  <include href="mouse_press_to_aisinglechoiceelement_choose.xml" start="true" />
  <!--include href="mouse_press_to_aisinglechoiceelement_unchoose.xml" start="true" /-->
  <include href="head_tilting_right_to_aisinglepresence_next.xml" start="true"/>
  <include href="head_tilting_left_to_aisinglepresence_prev.xml" start="true"/>
  <include href="head_looking_right_to_aisinglepresence_next.xml" start="true"/>
  <include href="head_looking_left_to_aisinglepresence_prev.xml" start="true"/>
  <include href="head_nodding_to_aisinglepresence_next.xml" start="true"/>

  <!-- Gesture-based Navigation -->
  <include href="onehandposnav_previous_to_aio_prev.xml" start="true"/>
  <include href="onehandposnav_next_to_aio_next.xml" start="true"/>
  <include href="onehandposnav_confirm_to_aichoiceelement_choose.xml" start="true"/>

  <!-- browser refresh handling -->
  <include href="caroufredsel_refreshing_to_caroufredsel_init_js.xml" start="true"/>
</mim>

=== sfeu/MINT-platform/core/model/mim/aisinglechoice_present_to_child_present.xml
<mapping name="AISingleChoice present to present active child" xmlns="http://www.multi-access.de" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.multi-access.de mint-mappings.xsd">
  <operator type="sequential" id="1">
    <observations>
      <observation id="2" interactor="Interactor.AIO.AIOUT.AIContainer.AISingleChoice" states="presenting" result="aisc" process="onchange"/>
      <observation id="3" type="negation" interactor="Interactor.AIO" name="aisc.children.first.name" states="presenting" result="active_child" process="instant"/>
    </observations>
    <actions>
      <backend id="5" call="present_children" class="AUIControl" parameter="aisc"/>
      <event id="6" type="children_finished" target="aisc"/>
    </actions>
  </operator>
</mapping>

=== sfeu/MINT-platform/core/model/mim/aisinglepresence_children_finished_to_caroufredsel_init_js.xml
<mapping name="AISinglePresence children finished to initjs CarouFredSel" xmlns="http://www.multi-access.de" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.multi-access.de mint-mappings.xsd">
  <operator type="sequential" id="1">
    <observations>
      <observation id="2" interactor="Interactor.AIO.AIOUT.AIContainer.AISinglePresence" states="children_finished" result="ais" process="onchange"/>
      <observation id="3" interactor="Interactor.CIO.CIC.CarouFredSel" name="ais.name" states="wait_for_children" result="cio" process="instant"/>
      <observation id="4" interactor="Interactor.CIO.Image.CarouFredSelImage" name="ais.active_child.name" states="displaying" result="page" process="continuous"/>
    </observations>
    <actions>
      <event id="5" type="init_js" target="cio"/>
    </actions>
  </operator>
</mapping>

=== sfeu/MINT-platform/core/model/mim/mouse_press_to_aisinglechoiceelement_unchoose.xml
<mapping name="Sync Mouse press to AISingleChoiceElement unchoose" xmlns="http://www.multi-access.de"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.multi-access.de mint-mappings.xsd">

  <operator type="sequential" id="1">
    <observations>
      <observation id="2" interactor="Interactor.IR.IRMode.Pointer.Mouse" states="left_pressed" result="m" process="onchange"/>
      <observation id="3" interactor="Interactor.AIO.AIIN.AIINDiscrete.AIReference.AIChoiceElement.AISingleChoiceElement" states="focused" result="sce" process="instant"/>
      <observation id="4" interactor="Interactor.AIO.AIIN.AIINDiscrete.AIReference.AIChoiceElement.AISingleChoiceElement" name="sce.name" result ="ttt" states="chosen" process="instant"/>
    </observations>
    <actions>
      <event id="5" type="unchoose" target="sce"/>
    </actions>
  </operator>

</mapping>
