=== sfeu/MINT-platform/core/model/mim/mint-mappings.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.multi-access.de" xmlns:mint="http://www.multi-access.de" elementFormDefault="qualified">

  <xs:element name="event">
    <xs:complexType>
      <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
      <xs:attribute name="type" type="xs:string" use="required"/>
      <xs:attribute name="target" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="backend">
    <xs:complexType>
      <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
      <xs:attribute name="call" type="xs:string" use="required"/>
      <xs:attribute name="class" type="xs:string" use="required"/>
      <xs:attribute name="parameter" type="xs:string"/>
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="processType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="onchange"/>
      <xs:enumeration value="continuous"/>
      <xs:enumeration value="instant"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="observationType">
      <xs:restriction base="xs:string">
        <xs:enumeration value="negation"/>
      </xs:restriction>
    </xs:simpleType>


  <xs:element name="observation"  >
    <xs:complexType>
      <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
      <xs:attribute name="interactor" type="xs:string" use="required"/>
      <xs:attribute name="name" type="xs:string" />
      <xs:attribute name="states" type="xs:string"/>
      <xs:attribute name="result" type="xs:string"/>
      <xs:attribute name="type" type="observationType"/>
      <xs:attribute name="process" type="processType"/>
    </xs:complexType>

  </xs:element>

  <xs:element name="bind" >
    <xs:complexType>
      <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
      <xs:attribute name="interactor_in" type="xs:string" use="required"/>
      <xs:attribute name="name_in" type="xs:string" use="required"/>
      <xs:attribute name="attr_in" type="xs:string" use="required"/>
      <xs:attribute name="interactor_out" type="xs:string" use="required"/>
      <xs:attribute name="transformation"  type="xs:string"/>  <!-- TODO: if exists transformation, class need to be there as well -->
      <xs:attribute name="class" type="xs:string" />
      <xs:attribute name="name_out" type="xs:string" use="required"/>
      <xs:attribute name="attr_out" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="observations">
    <xs:complexType>
      <xs:sequence minOccurs="1" maxOccurs="unbounded">
        <xs:element ref="mint:observation"  />
      </xs:sequence>
    </xs:complexType>
    <!-- TODO unique check does not work yet -->
    <!--xs:key name="key_Participant">
           <xs:selector xpath="./observation"/>
           <xs:field xpath="@id"/>
         </xs:key-->
  </xs:element>

  <xs:element name="actions">
    <xs:complexType>                           <xs:choice minOccurs="1" maxOccurs="unbounded">
        <xs:element ref="mint:bind" />
        <xs:element ref="mint:event" />
        <xs:element ref="mint:backend" />
      </xs:choice>
    </xs:complexType>
  </xs:element>

  <xs:element name="operator">
    <xs:complexType>
      <xs:sequence minOccurs="1" maxOccurs="1">
        <xs:element ref="mint:observations"/>
        <xs:element ref="mint:actions"/>
      </xs:sequence>
      <xs:attribute name="type" type="xs:string" use="required"/>
      <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="mapping">
     <xs:complexType>
       <xs:sequence>
         <xs:element minOccurs="1" maxOccurs="unbounded" ref="mint:operator"/>
       </xs:sequence>
       <xs:attribute name="name" type="xs:string" use="required"/>

     </xs:complexType>


   </xs:element>

  <xs:element name="include" >
      <xs:complexType>
        <xs:attribute name="href" type="xs:string" use="required"/>
        <xs:attribute name="start" type="xs:string" default="false"/>
      </xs:complexType>
    </xs:element>

  <xs:element name="mim">
     <xs:complexType>
       <xs:choice minOccurs="1" maxOccurs="unbounded">
         <xs:element ref="mint:mapping" />
         <xs:element ref="mint:include"/>
       </xs:choice>
       <xs:attribute name="name" type="xs:string" use="required"/>

     </xs:complexType>
   </xs:element>


</xs:schema>

=== sfeu/MINT-platform/core/model/mim/aio_present_to_cio_display.xml
<mapping name="Sync AIO present to CIO display" xmlns="http://www.multi-access.de" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.multi-access.de mint-mappings.xsd">
  <operator type="sequential" id="1">
    <observations>
      <observation id="2" interactor="Interactor.AIO" states="presenting" result="aio" process="onchange"/>
      <observation id="3" type="negation" interactor="Interactor.CIO" name="aio.name" states="displaying" result="cio" process="instant"/>
      <observation id="5" interactor="Interactor.AIO" states="presenting" name="aio.name"  process="instant"/>
    </observations>
    <actions>
      <event id="4" type="display" target="cio"/>
    </actions>
  </operator>
</mapping>

=== sfeu/MINT-platform/core/model/mim/cio_highlight_to_aio_focus.xml
<mapping name="Sync CIO highlight to AIO focused" xmlns="http://www.multi-access.de" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.multi-access.de mint-mappings.xsd">
  <operator type="sequential" id="1">
    <observations>
      <observation id="2" interactor="Interactor.CIO" states="highlighted" result="cio" process="onchange"/>
      <observation id="3" type="negation" interactor="Interactor.AIO" name="cio.name" states="focused" result="cio" process="instant"/>
      <observation id="5" interactor="Interactor.CIO" states="highlighted" name="cio.name" process="instant"/>
    </observations>
    <actions>
      <event id="4" type="focus" target="cio"/>
    </actions>
  </operator>
</mapping>

=== sfeu/MINT-platform/core/model/mim/caroufredsel_refreshing_to_caroufredsel_init_js.xml
<mapping name="CarouFredSel refreshing to initjs CarouFredSel" xmlns="http://www.multi-access.de" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.multi-access.de mint-mappings.xsd">
  <operator type="sequential" id="1">
    <observations>
      <observation id="3" interactor="Interactor.CIO.CIC.CarouFredSel" states="refreshing" result="cio" process="onchange"/>
      <observation id="2" interactor="Interactor.AIO.AIOUT.AIContainer.AISinglePresence" name="cio.name" result="ais" process="instant"/>
      <observation id="4" interactor="Interactor.CIO.Image.CarouFredSelImage" name="ais.active_child.name" states="displaying" result="page" process="continuous"/>
    </observations>
    <actions>
      <event id="5" type="init_js" target="cio"/>
    </actions>
  </operator>
</mapping>

=== sfeu/MINT-platform/core/model/mim/aio_focus_to_cio_highlight.xml
<mapping name="Sync AIO focus to CIO highlight" xmlns="http://www.multi-access.de" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.multi-access.de mint-mappings.xsd">
  <operator type="sequential" id="1">
    <observations>
      <observation id="2" interactor="Interactor.AIO" states="focused" result="aio" process="onchange"/>
      <observation id="3" type="negation" interactor="Interactor.CIO" name="aio.name" states="highlighted" result="cio" process="instant"/>
      <observation id="5" interactor="Interactor.AIO" states="focused" name="aio.name"  process="instant"/>
    </observations>
    <actions>
      <event id="4" type="highlight" target="cio"/>
    </actions>
  </operator>
</mapping>

=== sfeu/MINT-platform/core/model/mim/aisinglepresence_present_to_child_present.xml
<mapping name="AISinglePresence present to present active child" xmlns="http://www.multi-access.de" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.multi-access.de mint-mappings.xsd">
  <operator type="sequential" id="1">
    <observations>
      <observation id="2" interactor="Interactor.AIO.AIOUT.AIContainer.AISinglePresence" states="presenting" result="ais" process="onchange"/>
      <observation id="3" type="negation" interactor="Interactor.AIO" name="ais.active_child.name"  result="active_child" process="instant"/>
    </observations>
    <actions>
      <event id="4" type="present" target="active_child"/>
      <backend id="5" call="suspend_others" class="AUIControl" parameter="ais"/>
      <event id="6" type="children_finished" target="ais"/>
    </actions>
  </operator>
</mapping>

=== sfeu/MINT-platform/examples/luminar/mim/drag_mapping.xml
<mapping name="Move Mapping" xmlns="http://www.multi-access.de"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.multi-access.de ../../../../MINT-core/lib/MINT-core/model/mim/mint-mappings.xsd">
  <operator id = "1" type="sequential">
    <observations>
      <observation id="2" interactor="Interactor.IR.IRMode.Body.Hand.Fingertip" result="p" states="touched" process="onchange"/>
      <backend_observation id="10" call="find_cio_from_coordinates" class="CUIControl" result="cio" parameter="f.x,f.y"/>
      <observation id="4" interactor="Interactor.IR.IRMode.Body.Hand.Fingertip" name="p.name" states="moving" process="continuous"/>
   </observations>
   <terminate>
     <observations>
       <observation id="5" interactor="Interactor.IR.IRMode.Body.Hand.Fingertip" name="p.name" states="released" process="onchange"/>
     </observations>
     <actions>
     </actions>
   </terminate>
    <actions>
      <bind id="33" interactor_in="Interactor.IR.IRMode.Body.Hand.Fingertip" name_in="p.name" attr_in="x" interactor_out="Interactor.CIO" name_out="c.name" attr_out="x"/>
      <bind id="44" interactor_in="Interactor.IR.IRMode.Body.Hand.Fingertip" name_in="p.name" attr_in="y" interactor_out="Interactor.CIO" name_out="c.name" attr_out="y"/>
    </actions>
  </operator>

</mapping>
